SELECT LENGTH('sky');

SELECT UPPER('sky');

SELECT LOWER('SkY');

SELECT LTRIM('  SKY  ');

SELECT RTRIM('  SKY  ');

SELECT TRIM('  SKY  ');

SELECT LEFT('KINDERGARTEN', 5);

SELECT RIGHT('KINDERGARTEN', 5);

SELECT SUBSTRING('KINDERGARTEN', 3, 5);

SELECT SUBSTRING('KINDERGARTEN', 3);

SELECT LOCATE('n', 'KINDERGARTEN');

SELECT LOCATE('Q', 'KINDERGARTEN');

SELECT LOCATE('GARTEN', 'KINDERGARTEN');

SELECT REPLACE('KINDERGARTEN', 'T', 'D');

SELECT CONCAT('firstname', ' ', 'lastname') AS fullname;
