SELECT NOW(), CURDATE(), CURTIME();

SELECT YEAR(NOW()), MONTH(NOW()), DAY(NOW());

SELECT HOUR(NOW()), MINUTE(NOW()), SECOND(NOW());

SELECT MONTHNAME(NOW()), DAYNAME(NOW());

SELECT EXTRACT(DAY FROM NOW());
SELECT EXTRACT(MONTH FROM NOW());
SELECT EXTRACT(HOUR FROM NOW());


